apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopay-spa
  labels:
    app: shopay-spa
spec:
  replicas: 1 # number of desired replicas
  selector:
    matchLabels:
      app: shopay-spa
  template:
    metadata:
      labels:
        app: shopay-spa
    spec:
      containers:
        - name: shopay-spa
          image: ashok1201/shopay-spa # your frontend application Docker image
          ports:
            - containerPort: 3000 # the port your application listens to
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy # the OAuth2 proxy Docker image
          args:
            - --http-address=:8000 # the port your proxy listens to
            - --upstream=http://localhost:3000 # the upstream URL for your application
            - --upstream=http://localhost:8080 # add additional upstream URLs as needed
            - --email-domains = [ "*" ]
            - --upstreams = ["http://localhost:3000","http://localhost:3001/api/orders","http://localhost:3001/api/offers","http://localhost:3002/api/requests","http://localhost:3001/api/get" ]
            - --provider = "oidc"
            - --provider_display_name="Asgardeo"
            - --reverse_proxy = false
            - --redirect_url = "http://localhost:8000/spa_proxy/oauth2/callback"
            - --oidc_issuer_url = "https://api.asgardeo.io/t/akumar/oauth2/token"
            - --login_url="https://api.asgardeo.io/t/akumar/oauth2/authorize"
            - --redeem_url = "https://api.asgardeo.io/t/akumar/oauth2/token"
            - --profile_url= "https://api.asgardeo.io/t/akumar/oauth2/userinfo"
            - --validate_url= "https://api.asgardeo.io/t/akumar/oauth2/introspect"
            - --scope= "openid email"
            - --skip_auth_regex="/home|/cart|/static/js/*|/images/*|/api/get|/hospitalDashoard.php|/assets/*"
            - --skip_provider_button=true
          ports:
            - containerPort: 8000 # the port your proxy listens to
