version: "3"

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

services:
  myapp:
    build: /frontend
    ports:
      - "3000:80"
    networks:
      - mynetwork
      
  oauth2-proxy:
    build: /proxy
    restart: always
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - myapp
   


