version: "3"

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

services:
  
  oauth2-proxy:
    build: ./proxy
    restart: always
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    
      
   
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: shopay
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - mynetwork
    ports:
      - "3308:3306"
  
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"
    networks:
      - mynetwork
  
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
      - oauth2-proxy
      - api
    networks:
      - mynetwork
    command: sh -c "sleep 10 && node index.js"
  
  myapp:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - mynetwork
    depends_on:
      - backend
     
  api:
    build: ./api
    ports:
      - "4001:4001"
    networks:
      - mynetwork  
      