oauth2-proxy:
  image:
    repository: "quay.io/oauth2-proxy/oauth2-proxy"
    tag: ""
    pullPolicy: "IfNotPresent"

  fullnameOverride: "shopay-proxy"

  # Oauth client configuration specifics
  config:
    # Add config annotations
    annotations: {}
    # OAuth client ID
    clientID: ""
    # OAuth client secret
    clientSecret: ""
    cookieSecret: "5S5wk5A5O6MkKfZZ"
    cookieName: "oauth2_proxy"
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [
      "http://shopay-fe.shopay.svc.cluster.local:80",
      "http://shopay-backend.shopay.svc.cluster.local:3001/api/orders",
      "http://shopay-backend.shopay.svc.cluster.local:3001/api/offers",
      "http://shopay-backend.shopay.svc.cluster.local:3001/api/get",
      "http://shopay-backend.shopay.svc.cluster.local:3001/api/getProduct",
      "http://shopay-backend.shopay.svc.cluster.local:3001/api/getCustomAttribute",
      "http://shopay-api.shopay.svc.cluster.local:4001/secured_api"]
      provider = "oidc"
      redirect_url = "https://sample-app.local/oauth2/callback"
      oidc_issuer_url = ""
      scope= "openid email"
      skip_auth_regex="/home,/cart,/static/*,/product/*,/api/getProduct,/api/getCustomAttribute,/images/*,/api/get"
      skip_provider_button=true
      pass_access_token=true
      pass_authorization_header=true
      pass_basic_auth=true
      pass_user_headers=true

  service:
    type: ClusterIP
    portNumber: 4443
    appProtocol: http

  ingress:
    enabled: true
    className: nginx
    path: /
    pathType: ImplementationSpecific
    hosts:
      - sample-app.local
    labels: {}
    tls: 
      - secretName: tls-cert-spa-app
        hosts:
          - sample-app.local

shopay-fe:
  image:
    repository: ashok1201/shopay-fe
    pullPolicy: IfNotPresent
    tag: "1.0"

  fullnameOverride: "shopay-fe"

  service:
    type: ClusterIP
    port: 80

  env:
    HTTP_PROXY: https://sample-app.local

shopay-backend:
  image:
    repository: ashok1201/shopay-backend
    pullPolicy: IfNotPresent
    tag: "1.0"

  fullnameOverride: "shopay-backend"

  service:
    type: ClusterIP
    port: 3001

  env:
    HOST : shopay-db
    PORT : 3306
    USER : root
    PASSWORD : pass
    DATABASE : shopay
    URL : http://shopay-proxy.shopay.svc.cluster.local:4443/secured_api

shopay-api:
  image:
    repository: ashok1201/shopay-api
    pullPolicy: IfNotPresent
    tag: "1.0"

  fullnameOverride: "shopay-api"

  service:
    type: ClusterIP
    port: 4001
  
shopay-db:
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: "latest"

  fullnameOverride: "shopay-db"

  service:
    type: ClusterIP
    port: 3306
  
  env:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: shopay
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
    MYSQL_TCP_PORT: 3306

shopay-admin:
  image:
    repository: adminer
    pullPolicy: IfNotPresent
    tag: "latest"

  fullnameOverride: "shopay-admin"

  service:
    type: ClusterIP
    port: 8080
  
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    hosts:
      - host: spa.admin.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - secretName: tls-cert-admin
        hosts:
          - spa.admin.com