oauth2-proxy:
  fullnameOverride: "shopay-proxy"

  # Oauth client configuration specifics
  config:
    # Add config annotations
    annotations: {}
    # OAuth client ID
    clientID: "880386795823-olrdr7047el8skubcoaa02avc13lql6b.apps.googleusercontent.com"
    # OAuth client secret
    clientSecret: "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"
    cookieSecret: "5S5wk5A5O6MkKfZZ"
    cookieName: "oauth2_proxy"
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [
      "http://shopay-fe.default.svc.cluster.local:80",
      "http://shopay-backend.default.svc.cluster.local:3001/api/orders",
      "http://shopay-backend.default.svc.cluster.local:3001/api/offers",
      "http://shopay-backend.default.svc.cluster.local:3001/api/get",
      "http://shopay-backend.default.svc.cluster.local:3001/api/getProduct",
      "http://shopay-backend.default.svc.cluster.local:3001/api/getCustomAttribute",
      "http://shopay-api.default.svc.cluster.local:4001/secured_api"]
      provider = "oidc"
      provider_display_name="Asgardeo"
      reverse_proxy = false
      redirect_url = "https://spa.proxy.com/oauth2/callback"
      oidc_issuer_url = "https://accounts.google.com"
      scope= "openid email"
      skip_auth_regex="/home,/cart,/static/*,/product/*,/api/getProduct,/api/getCustomAttribute,/images/*,/api/get"
      skip_provider_button=true
      pass_access_token=true
      pass_authorization_header=true
      pass_basic_auth=true
      pass_user_headers=true

  service:
    type: ClusterIP
    portNumber: 4443
    appProtocol: http

  ingress:
    enabled: true
    className: nginx
    path: /
    pathType: ImplementationSpecific
    hosts:
      - spa.proxy.com
    labels: {}
    tls: 
      - secretName: tls-cert-proxy
        hosts:
          - spa.proxy.com

shopay-fe:
  fullnameOverride: "shopay-fe"

  service:
    type: ClusterIP
    port: 80

  env:
    HTTP_PROXY: https://spa.proxy.com

shopay-backend:
  fullnameOverride: "shopay-backend"

  service:
    type: ClusterIP
    port: 3001

  env:
    HOST : shopay-db
    PORT : 3306
    USER : root
    PASSWORD : pass
    DATABASE : shopay
    URL : http://shopay-proxy.default.svc.cluster.local:4443/secured_api

shopay-api:
  fullnameOverride: "shopay-api"

  service:
    type: ClusterIP
    port: 4001
  
shopay-db:
  fullnameOverride: "shopay-db"

  service:
    type: ClusterIP
    port: 3306
  
  env:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: shopay
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

shopay-admin:
  fullnameOverride: "shopay-admin"

  service:
    type: ClusterIP
    port: 8080
  
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    hosts:
      - host: spa.admin.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - secretName: tls-cert-admin
        hosts:
          - spa.admin.com