name: oauth2-proxy
version: 6.10.1
apiVersion: v2
appVersion: 7.4.0
home: https://oauth2-proxy.github.io/oauth2-proxy/
description: A reverse proxy that provides authentication with Google, Github or other providers
keywords:
  - kubernetes
  - oauth
  - oauth2
  - authentication
  - google
  - github
  - redis

sources:
  - https://github.com/oauth2-proxy/oauth2-proxy
  - https://github.com/oauth2-proxy/manifests
maintainers:
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: tlawrie
  - name: NickMeves
    email: nicholas.meves@gmail.com
  - name: JoelSpeed
    email: joel.speed@hotmail.co.uk
  - name: pierluigilenoci
    email: pierluigi.lenoci@gmail.com
kubeVersion: ">=1.9.0-0"
